name: Daily Bot

on:
    schedule:
        - cron: '59 21 * * *'
        - cron: '59 22 * * *'
        - cron: '59 00 * * *'
        - cron: '59 23 * * *'
        - cron: '59 01 * * *'
    push:
        branches:
            - main

jobs:
    run-bot:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.x'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run bot
              env:
                TOKEN: ${{ secrets.TOKEN }}
                CHAT_ID: ${{ secrets.CHAT_ID }}
              run: python test.py