name: Python Script Example

on:
  push:
    branches:
      - main  # Pokreće se na svaki push na main granu

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Postavite odgovarajuću verziju Pythona

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ako postoji requirements.txt sa potrebnim paketima

      - name: Run Python script
        run: python main.py
